//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace FFmpeg
{
    public unsafe static partial class libavutil
    {
        [StructLayout(LayoutKind.Sequential)]
        public unsafe partial struct AVMotionVector
        {
            /// <summary>
            /// Where the current macroblock comes from; negative value when it comes
            /// from the past, positive value when it comes from the future.
            /// XXX: set exact relative ref frame reference instead of a +/- 1
            /// "direction".
            /// </summary>
            public int source;

            /// <summary>
            /// Width and height of the block.
            /// </summary>
            public byte w;

            /// <summary>
            /// Width and height of the block.
            /// </summary>
            public byte h;

            /// <summary>
            /// Absolute source position. Can be outside the frame area.
            /// </summary>
            public short src_x;

            /// <summary>
            /// Absolute source position. Can be outside the frame area.
            /// </summary>
            public short src_y;

            /// <summary>
            /// Absolute destination position. Can be outside the frame area.
            /// </summary>
            public short dst_x;

            /// <summary>
            /// Absolute destination position. Can be outside the frame area.
            /// </summary>
            public short dst_y;

            /// <summary>
            /// Extra flag information.
            /// Currently unused.
            /// </summary>
            public ulong flags;
        }
    }
}
