//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;
using FFmpeg;

namespace FFmpeg
{
    public unsafe static partial class libswscale
    {
        public const sbyte LIBSWSCALE_VERSION_MAJOR = 3;

        public const sbyte LIBSWSCALE_VERSION_MINOR = 0;

        public const sbyte LIBSWSCALE_VERSION_MICRO = 100;
    }
}
