//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
// ReSharper disable RedundantUsingDirective
// ReSharper disable CheckNamespace
#pragma warning disable 1584,1711,1572,1581,1580,1573
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace FFmpeg
{
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("ReSharper", "UnusedMember.Global")]
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("ReSharper", "InconsistentNaming")]
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("ReSharper", "RedundantUnsafeContext")]
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("ReSharper", "MemberCanBePrivate.Global")]
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("ReSharper", "MemberCanBePrivate.Global")]
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("ReSharper", "FieldCanBeMadeReadOnly.Global")]
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("ReSharper", "PartialTypeWithSinglePart")]
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("ReSharper", "RedundantNameQualifier")]
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("ReSharper", "ArrangeModifiersOrder")]
    public unsafe static partial class libavutil
    {
        /// <summary>
        /// Mastering display metadata capable of representing the color volume of
        /// the display used to master the content (SMPTE 2086:2014).
        /// 
        /// To be used as payload of a AVFrameSideData or AVPacketSideData with the
        /// appropriate type.
        /// </summary>
        /// <remark>
        /// The struct should be allocated with
        /// av_mastering_display_metadata_alloc()
        /// and its size is not a part of the public ABI.
        /// </remark>
        [StructLayout(LayoutKind.Sequential)]
        public unsafe partial struct AVMasteringDisplayMetadata
        {
            /// <summary>
            /// CIE 1931 xy chromaticity coords of color primaries (r, g, b order).
            /// </summary>
            public libavutil.ArrayWrapper_AVRational__3 display_primaries;

            /// <summary>
            /// CIE 1931 xy chromaticity coords of white point.
            /// </summary>
            public libavutil.ArrayWrapper_AVRational2 white_point;

            /// <summary>
            /// Min luminance of mastering display (cd/m^2).
            /// </summary>
            public libavutil.AVRational min_luminance;

            /// <summary>
            /// Max luminance of mastering display (cd/m^2).
            /// </summary>
            public libavutil.AVRational max_luminance;

            /// <summary>
            /// Flag indicating whether the display primaries (and white point) are
            /// set.
            /// </summary>
            public int has_primaries;

            /// <summary>
            /// Flag indicating whether the luminance (min_ and max_) have been set.
            /// </summary>
            public int has_luminance;
        }

        /// <summary>
        /// Allocate an AVMasteringDisplayMetadata structure and set its fields to
        /// default values. The resulting struct can be freed using av_freep().
        /// </summary>
        /// <returns>
        /// An AVMasteringDisplayMetadata filled with default values or NULL
        /// on failure.
        /// </returns>
        [SuppressUnmanagedCodeSecurity]
        [DllImport(AVUTIL_DLL_NAME, CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            CharSet = CharSet.Ansi, ExactSpelling = true,
            EntryPoint="av_mastering_display_metadata_alloc")]
        public static extern libavutil.AVMasteringDisplayMetadata* av_mastering_display_metadata_alloc();

        /// <summary>
        /// Allocate a complete AVMasteringDisplayMetadata and add it to the frame.
        /// </summary>
        /// <param name="frame">
        /// The frame which side data is added to.
        /// </param>
        /// <returns>
        /// The AVMasteringDisplayMetadata structure to be filled by caller.
        /// </returns>
        [SuppressUnmanagedCodeSecurity]
        [DllImport(AVUTIL_DLL_NAME, CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            CharSet = CharSet.Ansi, ExactSpelling = true,
            EntryPoint="av_mastering_display_metadata_create_side_data")]
        public static extern libavutil.AVMasteringDisplayMetadata* av_mastering_display_metadata_create_side_data(libavutil.AVFrame* frame);
    }
}
