//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
// ReSharper disable RedundantUsingDirective
// ReSharper disable CheckNamespace
#pragma warning disable 1584,1711,1572,1581,1580,1573
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace FFmpeg
{
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("ReSharper", "UnusedMember.Global")]
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("ReSharper", "InconsistentNaming")]
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("ReSharper", "RedundantUnsafeContext")]
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("ReSharper", "MemberCanBePrivate.Global")]
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("ReSharper", "MemberCanBePrivate.Global")]
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("ReSharper", "FieldCanBeMadeReadOnly.Global")]
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("ReSharper", "PartialTypeWithSinglePart")]
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("ReSharper", "RedundantNameQualifier")]
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("ReSharper", "ArrangeModifiersOrder")]
    public unsafe static partial class libavutil
    {
        [StructLayout(LayoutKind.Sequential)]
        public unsafe partial struct AVMD5
        {
        }

        /// <summary>
        /// Allocate an AVMD5 context.
        /// </summary>
        [SuppressUnmanagedCodeSecurity]
        [DllImport(AVUTIL_DLL_NAME, CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            CharSet = CharSet.Ansi, ExactSpelling = true,
            EntryPoint="av_md5_alloc")]
        public static extern libavutil.AVMD5* av_md5_alloc();

        /// <summary>
        /// Initialize MD5 hashing.
        /// </summary>
        /// <param name="ctx">
        /// pointer to the function context (of size av_md5_size)
        /// </param>
        [SuppressUnmanagedCodeSecurity]
        [DllImport(AVUTIL_DLL_NAME, CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            CharSet = CharSet.Ansi, ExactSpelling = true,
            EntryPoint="av_md5_init")]
        public static extern void av_md5_init(libavutil.AVMD5* ctx);

        /// <summary>
        /// Update hash value.
        /// </summary>
        /// <param name="ctx">
        /// hash function context
        /// </param>
        /// <param name="src">
        /// input data to update hash with
        /// </param>
        /// <param name="len">
        /// input data length
        /// </param>
        [SuppressUnmanagedCodeSecurity]
        [DllImport(AVUTIL_DLL_NAME, CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            CharSet = CharSet.Ansi, ExactSpelling = true,
            EntryPoint="av_md5_update")]
        public static extern void av_md5_update(libavutil.AVMD5* ctx, byte* src, int len);

        /// <summary>
        /// Finish hashing and output digest value.
        /// </summary>
        /// <param name="ctx">
        /// hash function context
        /// </param>
        /// <param name="dst">
        /// buffer where output digest value is stored
        /// </param>
        [SuppressUnmanagedCodeSecurity]
        [DllImport(AVUTIL_DLL_NAME, CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            CharSet = CharSet.Ansi, ExactSpelling = true,
            EntryPoint="av_md5_final")]
        public static extern void av_md5_final(libavutil.AVMD5* ctx, byte* dst);

        /// <summary>
        /// Hash an array of data.
        /// </summary>
        /// <param name="dst">
        /// The output buffer to write the digest into
        /// </param>
        /// <param name="src">
        /// The data to hash
        /// </param>
        /// <param name="len">
        /// The length of the data, in bytes
        /// </param>
        [SuppressUnmanagedCodeSecurity]
        [DllImport(AVUTIL_DLL_NAME, CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            CharSet = CharSet.Ansi, ExactSpelling = true,
            EntryPoint="av_md5_sum")]
        public static extern void av_md5_sum(byte* dst, byte* src, int len);
    }
}
