//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace libavutil
{
    public unsafe partial class libavutil
    {
        /// <summary>
        /// Calculate the Adler32 checksum of a buffer.
        /// 
        /// Passing the return value to a subsequent av_adler32_update() call
        /// allows the checksum of multiple buffers to be calculated as though
        /// they were concatenated.
        /// 
        /// @param adler initial checksum value
        /// @param buf   pointer to input buffer
        /// @param len   size of input buffer
        /// @return      updated checksum
        /// </summary>
        [SuppressUnmanagedCodeSecurity]
        [DllImport("avutil-if-52.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="av_adler32_update")]
        internal static extern uint av_adler32_update(uint adler, byte* buf, uint len);
    }
}
