//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace libavutil
{
    public unsafe partial class libavutil
    {
        /// <summary>
        /// @brief Decodes LZO 1x compressed data.
        /// @param out output buffer
        /// @param outlen size of output buffer, number of bytes left are returned
        /// here
        /// @param in input buffer
        /// @param inlen size of input buffer, number of bytes left are returned
        /// here
        /// @return 0 on success, otherwise a combination of the error flags above
        /// 
        /// Make sure all buffers are appropriately padded, in must provide
        /// AV_LZO_INPUT_PADDING, out must provide AV_LZO_OUTPUT_PADDING additional
        /// bytes.
        /// </summary>
        [SuppressUnmanagedCodeSecurity]
        [DllImport("avutil-if-52.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="av_lzo1x_decode")]
        internal static extern int av_lzo1x_decode(global::System.IntPtr @out, int* outlen, global::System.IntPtr @in, int* inlen);
    }
}
