//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace libavutil
{
    [StructLayout(LayoutKind.Explicit)]
    public unsafe partial struct AVRIPEMD
    {
    }

    public unsafe partial class libavutil
    {
        /// <summary>
        /// Allocate an AVRIPEMD context.
        /// </summary>
        [SuppressUnmanagedCodeSecurity]
        [DllImport("avutil-if-52.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="av_ripemd_alloc")]
        internal static extern AVRIPEMD* av_ripemd_alloc();

        /// <summary>
        /// Initialize RIPEMD hashing.
        /// 
        /// @param context pointer to the function context (of size av_ripemd_size)
        /// @param bits    number of bits in digest (128, 160, 256 or 320 bits)
        /// @return        zero if initialization succeeded, -1 otherwise
        /// </summary>
        [SuppressUnmanagedCodeSecurity]
        [DllImport("avutil-if-52.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="av_ripemd_init")]
        internal static extern int av_ripemd_init(AVRIPEMD* context, int bits);

        /// <summary>
        /// Update hash value.
        /// 
        /// @param context hash function context
        /// @param data    input data to update hash with
        /// @param len     input data length
        /// </summary>
        [SuppressUnmanagedCodeSecurity]
        [DllImport("avutil-if-52.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="av_ripemd_update")]
        internal static extern void av_ripemd_update(AVRIPEMD* context, byte* data, uint len);

        /// <summary>
        /// Finish hashing and output digest value.
        /// 
        /// @param context hash function context
        /// @param digest  buffer where output digest value is stored
        /// </summary>
        [SuppressUnmanagedCodeSecurity]
        [DllImport("avutil-if-52.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="av_ripemd_final")]
        internal static extern void av_ripemd_final(AVRIPEMD* context, byte* digest);
    }
}
