//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace FFmpeg
{
    public unsafe static partial class libavdevice
    {
        /// <summary>
        /// Return the LIBAVDEVICE_VERSION_INT constant.
        /// </summary>
        [SuppressUnmanagedCodeSecurity]
        [DllImport(AVDEVICE_DLL_NAME, CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            CharSet = CharSet.Ansi, ExactSpelling = true,
            EntryPoint="avdevice_version")]
        public static extern uint avdevice_version();

        /// <summary>
        /// Return the libavdevice build-time configuration.
        /// </summary>
        [SuppressUnmanagedCodeSecurity]
        [DllImport(AVDEVICE_DLL_NAME, CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            CharSet = CharSet.Ansi, ExactSpelling = true,
            EntryPoint="avdevice_configuration")]
        public static extern sbyte* avdevice_configuration();

        /// <summary>
        /// Return the libavdevice license.
        /// </summary>
        [SuppressUnmanagedCodeSecurity]
        [DllImport(AVDEVICE_DLL_NAME, CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            CharSet = CharSet.Ansi, ExactSpelling = true,
            EntryPoint="avdevice_license")]
        public static extern sbyte* avdevice_license();

        /// <summary>
        /// Initialize libavdevice and register all the input and output devices.
        /// @warning This function is not thread safe.
        /// </summary>
        [SuppressUnmanagedCodeSecurity]
        [DllImport(AVDEVICE_DLL_NAME, CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            CharSet = CharSet.Ansi, ExactSpelling = true,
            EntryPoint="avdevice_register_all")]
        public static extern void avdevice_register_all();
    }
}
