//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace FFmpeg
{
    public unsafe static partial class libavdevice
    {
        public const sbyte LIBAVDEVICE_VERSION_MAJOR = 54;

        public const sbyte LIBAVDEVICE_VERSION_MINOR = 2;

        public const sbyte LIBAVDEVICE_VERSION_MICRO = 101;
    }
}
