//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace FFmpeg
{
    public unsafe static partial class libavutil
    {
        [StructLayout(LayoutKind.Sequential)]
        public unsafe partial struct AVSHA512
        {
        }

        /// <summary>
        /// Allocate an AVSHA512 context.
        /// </summary>
        [SuppressUnmanagedCodeSecurity]
        [DllImport(AVUTIL_DLL_NAME, CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            CharSet = CharSet.Ansi, ExactSpelling = true,
            EntryPoint="av_sha512_alloc")]
        public static extern libavutil.AVSHA512* av_sha512_alloc();

        /// <summary>
        /// Initialize SHA-2 512 hashing.
        /// </summary>
        /// <param name="context">
        /// pointer to the function context (of size av_sha512_size)
        /// </param>
        /// <param name="bits">
        /// number of bits in digest (224, 256, 384 or 512 bits)
        /// </param>
        /// <returns>
        /// zero if initialization succeeded, -1 otherwise
        /// </returns>
        [SuppressUnmanagedCodeSecurity]
        [DllImport(AVUTIL_DLL_NAME, CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            CharSet = CharSet.Ansi, ExactSpelling = true,
            EntryPoint="av_sha512_init")]
        public static extern int av_sha512_init(libavutil.AVSHA512* context, int bits);

        /// <summary>
        /// Update hash value.
        /// </summary>
        /// <param name="context">
        /// hash function context
        /// </param>
        /// <param name="data">
        /// input data to update hash with
        /// </param>
        /// <param name="len">
        /// input data length
        /// </param>
        [SuppressUnmanagedCodeSecurity]
        [DllImport(AVUTIL_DLL_NAME, CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            CharSet = CharSet.Ansi, ExactSpelling = true,
            EntryPoint="av_sha512_update")]
        public static extern void av_sha512_update(libavutil.AVSHA512* context, byte* data, uint len);

        /// <summary>
        /// Finish hashing and output digest value.
        /// </summary>
        /// <param name="context">
        /// hash function context
        /// </param>
        /// <param name="digest">
        /// buffer where output digest value is stored
        /// </param>
        [SuppressUnmanagedCodeSecurity]
        [DllImport(AVUTIL_DLL_NAME, CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            CharSet = CharSet.Ansi, ExactSpelling = true,
            EntryPoint="av_sha512_final")]
        public static extern void av_sha512_final(libavutil.AVSHA512* context, byte* digest);
    }
}
