//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace libavutil
{
    public enum AVCRCId
    {
        AV_CRC_8_ATM = 0,
        AV_CRC_16_ANSI = 1,
        AV_CRC_16_CCITT = 2,
        AV_CRC_32_IEEE = 3,
        AV_CRC_32_IEEE_LE = 4,
        AV_CRC_MAX = 5
    }

    public unsafe partial class libavutil
    {
        [SuppressUnmanagedCodeSecurity]
        [DllImport("avutil-if-51.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="av_crc_init")]
        internal static extern int av_crc_init(uint* ctx, int le, int bits, uint poly, int ctx_size);

        [SuppressUnmanagedCodeSecurity]
        [DllImport("avutil-if-51.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="av_crc_get_table")]
        internal static extern uint* av_crc_get_table(AVCRCId crc_id);

        [SuppressUnmanagedCodeSecurity]
        [DllImport("avutil-if-51.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="av_crc")]
        internal static extern uint av_crc(uint* ctx, uint start_crc, byte* buffer, uint length);
    }
}
