//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace libavutil
{
    [StructLayout(LayoutKind.Explicit)]
    public unsafe partial struct av_alias64
    {
        [FieldOffset(0)]
        public ulong u64;

        [FieldOffset(0)]
        public fixed uint u32[2];

        [FieldOffset(0)]
        public fixed ushort u16[4];

        [FieldOffset(0)]
        public fixed byte u8[8];

        [FieldOffset(0)]
        public double f64;

        [FieldOffset(0)]
        public fixed float f32[2];

        [FieldOffset(0)]
        private ulong u64;

        [FieldOffset(0)]
        private uint[] u32;

        [FieldOffset(0)]
        private ushort[] u16;

        [FieldOffset(0)]
        private byte[] u8;

        [FieldOffset(0)]
        private double f64;

        [FieldOffset(0)]
        private float[] f32;
    }

    [StructLayout(LayoutKind.Explicit)]
    public unsafe partial struct av_alias32
    {
        [FieldOffset(0)]
        public uint u32;

        [FieldOffset(0)]
        public fixed ushort u16[2];

        [FieldOffset(0)]
        public fixed byte u8[4];

        [FieldOffset(0)]
        public float f32;

        [FieldOffset(0)]
        private uint u32;

        [FieldOffset(0)]
        private ushort[] u16;

        [FieldOffset(0)]
        private byte[] u8;

        [FieldOffset(0)]
        private float f32;
    }

    [StructLayout(LayoutKind.Explicit)]
    public unsafe partial struct av_alias16
    {
        [FieldOffset(0)]
        public ushort u16;

        [FieldOffset(0)]
        public fixed byte u8[2];

        [FieldOffset(0)]
        private ushort u16;

        [FieldOffset(0)]
        private byte[] u8;
    }
}
