//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace libavutil
{
    public unsafe partial class libavutil
    {
        /// <summary>
        /// @brief Decodes LZO 1x compressed data.
        /// @param out output buffer
        /// @param outlen size of output buffer, number of bytes left are returned
        /// here
        /// @param in input buffer
        /// @param inlen size of input buffer, number of bytes left are returned
        /// here
        /// @return 0 on success, otherwise a combination of the error flags above
        /// 
        /// Make sure all buffers are appropriately padded, in must provide
        /// AV_LZO_INPUT_PADDING, out must provide AV_LZO_OUTPUT_PADDING additional
        /// bytes.
        /// </summary>
        [SuppressUnmanagedCodeSecurity]
        [DllImport("avutil-if-51.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="av_lzo1x_decode")]
        internal static extern int av_lzo1x_decode(global::System.IntPtr @out, int* outlen, global::System.IntPtr @in, int* inlen);

        /// <summary>
        /// @brief deliberately overlapping memcpy implementation
        /// @param dst destination buffer; must be padded with 12 additional bytes
        /// @param back how many bytes back we start (the initial size of the
        /// overlapping window), must be > 0
        /// @param cnt number of bytes to copy, must be >= 0
        /// 
        /// cnt > back is valid, this will copy the bytes we just copied,
        /// thus creating a repeating pattern with a period length of back.
        /// </summary>
        [SuppressUnmanagedCodeSecurity]
        [DllImport("avutil-if-51.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="av_memcpy_backptr")]
        internal static extern void av_memcpy_backptr(byte* dst, int back, int cnt);
    }
}
