//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace FFmpeg
{
    public unsafe static partial class libavutil
    {
        /// <summary>
        /// Get a seed to use in conjunction with random functions.
        /// This function tries to provide a good seed at a best effort bases.
        /// Its possible to call this function multiple times if more bits are
        /// needed.
        /// It can be quite slow, which is why it should only be used as seed for a
        /// faster
        /// PRNG. The quality of the seed depends on the platform.
        /// </summary>
        [SuppressUnmanagedCodeSecurity]
        [DllImport(AVUTIL_DLL_NAME, CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            CharSet = CharSet.Ansi, ExactSpelling = true,
            EntryPoint="av_get_random_seed")]
        public static extern uint av_get_random_seed();
    }
}
