//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace FFmpeg
{
    public unsafe static partial class libavutil
    {
        /// <summary>
        /// Calculate the Adler32 checksum of a buffer.
        /// 
        /// Passing the return value to a subsequent av_adler32_update() call
        /// allows the checksum of multiple buffers to be calculated as though
        /// they were concatenated.
        /// </summary>
        /// <param name="adler">
        /// initial checksum value
        /// </param>
        /// <param name="buf">
        /// pointer to input buffer
        /// </param>
        /// <param name="len">
        /// size of input buffer
        /// </param>
        /// <returns>
        /// updated checksum
        /// </returns>
        [SuppressUnmanagedCodeSecurity]
        [DllImport(AVUTIL_DLL_NAME, CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            CharSet = CharSet.Ansi, ExactSpelling = true,
            EntryPoint="av_adler32_update")]
        public static extern uint av_adler32_update(uint adler, byte* buf, uint len);
    }
}
