//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;
using FFmpeg;

namespace FFmpeg
{
    public unsafe static partial class libavcodec
    {
        [StructLayout(LayoutKind.Sequential)]
        public unsafe partial struct AVDVProfile
        {
            public int dsf;

            public int video_stype;

            public int frame_size;

            public int difseg_size;

            public int n_difchan;

            public libavutil.AVRational time_base;

            public int ltc_divisor;

            public int height;

            public int width;

            public libavutil.ArrayWrapper_AVRational2 sar;

            public libavutil.AVPixelFormat pix_fmt;

            public int bpm;

            public byte* block_sizes;

            public int audio_stride;

            public fixed int audio_min_samples[3];

            public fixed int audio_samples_dist[5];

            public fixed byte audio_shuffle[9];
        }

        [SuppressUnmanagedCodeSecurity]
        [DllImport(AVCODEC_DLL_NAME, CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            CharSet = CharSet.Ansi, ExactSpelling = true,
            EntryPoint="avpriv_dv_frame_profile2")]
        public static extern libavcodec.AVDVProfile* avpriv_dv_frame_profile2(libavcodec.AVCodecContext* codec, libavcodec.AVDVProfile* sys, byte* frame, uint buf_size);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(AVCODEC_DLL_NAME, CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            CharSet = CharSet.Ansi, ExactSpelling = true,
            EntryPoint="avpriv_dv_frame_profile")]
        public static extern libavcodec.AVDVProfile* avpriv_dv_frame_profile(libavcodec.AVDVProfile* sys, byte* frame, uint buf_size);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(AVCODEC_DLL_NAME, CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            CharSet = CharSet.Ansi, ExactSpelling = true,
            EntryPoint="avpriv_dv_codec_profile")]
        public static extern libavcodec.AVDVProfile* avpriv_dv_codec_profile(libavcodec.AVCodecContext* codec);

        /// <summary>
        /// Get a DV profile for the provided compressed frame.
        /// </summary>
        /// <param name="sys">
        /// the profile used for the previous frame, may be NULL
        /// </param>
        /// <param name="frame">
        /// the compressed data buffer
        /// </param>
        /// <param name="buf_size">
        /// size of the buffer in bytes
        /// </param>
        /// <returns>
        /// the DV profile for the supplied data or NULL on failure
        /// </returns>
        [SuppressUnmanagedCodeSecurity]
        [DllImport(AVCODEC_DLL_NAME, CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            CharSet = CharSet.Ansi, ExactSpelling = true,
            EntryPoint="av_dv_frame_profile")]
        public static extern libavcodec.AVDVProfile* av_dv_frame_profile(libavcodec.AVDVProfile* sys, byte* frame, uint buf_size);

        /// <summary>
        /// Get a DV profile for the provided stream parameters.
        /// </summary>
        [SuppressUnmanagedCodeSecurity]
        [DllImport(AVCODEC_DLL_NAME, CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            CharSet = CharSet.Ansi, ExactSpelling = true,
            EntryPoint="av_dv_codec_profile")]
        public static extern libavcodec.AVDVProfile* av_dv_codec_profile(int width, int height, libavutil.AVPixelFormat pix_fmt);
    }
}
